const liMenu = [
   { id : 1 , title : "پیشخوان" , link : "/"},
   { id : 2 , title : "کاربران" ,link : "users"},
   { id : 3 , title : "دسته بندی ها" ,link : "categoris"},
   { id : 4 , title : "گزارشات" , link : "/gozareshat"},
   { id : 5 , title : "کد های تخفیف" , link : "/offers"},
   { id : 6 , title : "تیکت ها" , link : "/tikets"},
   { id : 7 , title : "محصولات ما" , link : "InventoryBox"},
    
]


const dataDashboardMain = [
   { id : 1 , title : "مجموع فروش امروز" , count : 32_850_000 , percent : 15},
   { id : 1 , title : "تعداد محصولات" , count : 56 , percent : -30},
   { id : 2 , title : "کابران امروز" , count : 25 , percent : 37},
   { id : 3 , title : "بازدید امروز" , count : 329 , percent : 48},
    
]

const users = [
  { id: 1, name: "مبین", email: "mobin@example.com", role: 1 },
  { id: 2, name: "سارا", email: "sara@example.com", role: 1 },
  { id: 3, name: "علی", email: "ali@example.com", role: 1 },
  { id: 4, name: "ریحانه", email: "reyhaneh@example.com", role: 1 },
  { id: 5, name: "امیر", email: "amir@example.com", role: 1 },

  { id: 6, name: "زهرا", email: "zahra@example.com", role: 0 },
  { id: 7, name: "حسین", email: "hossein@example.com", role: 0 },
  { id: 8, name: "مهدی", email: "mahdi@example.com", role: 0 },
  { id: 9, name: "نگار", email: "negar@example.com", role: 0 },
  { id: 10, name: "پارسا", email: "parsa@example.com", role: 0 },
  { id: 11, name: "نازنین", email: "nazanin@example.com", role: 0 },
  { id: 12, name: "علیرضا", email: "alireza@example.com", role: 0 },
  { id: 13, name: "فاطمه", email: "fatemeh@example.com", role: 0 },
  { id: 14, name: "رضا", email: "reza@example.com", role: 0 },
  { id: 15, name: "مینا", email: "mina@example.com", role: 0 },

  { id: 16, name: "نیما", email: "nima@example.com", role: 0 },
  { id: 17, name: "شایان", email: "shayan@example.com", role: 0 },
  { id: 18, name: "الهام", email: "elham@example.com", role: 0 },
  { id: 19, name: "بابک", email: "babak@example.com", role: 0 },
  { id: 20, name: "مریم", email: "maryam@example.com", role: 0 },

  { id: 21, name: "سامان", email: "saman@example.com", role: 0 },
  { id: 22, name: "سحر", email: "sahar@example.com", role: 0 },
  { id: 23, name: "پویا", email: "pooya@example.com", role: 0 },
  { id: 24, name: "رها", email: "raha@example.com", role: 0 },
  { id: 25, name: "فرزاد", email: "farzad@example.com", role: 0 },

  { id: 26, name: "نیلوفر", email: "niloufar@example.com", role: 0 },
  { id: 27, name: "حمید", email: "hamid@example.com", role: 0 },
  { id: 28, name: "آرمان", email: "arman@example.com", role: 0 },
  { id: 29, name: "بهناز", email: "behnaz@example.com", role: 0 },
  { id: 30, name: "کریم", email: "karim@example.com", role: 0 },

  { id: 31, name: "لیلا", email: "leila@example.com", role: 0 },
  { id: 32, name: "مژگان", email: "mojgan@example.com", role: 0 },
  { id: 33, name: "فرهاد", email: "farhad@example.com", role: 0 },
  { id: 34, name: "آتنا", email: "atena@example.com", role: 0 },
  { id: 35, name: "سامیار", email: "samyar@example.com", role: 0 },

  { id: 36, name: "نرگس", email: "narges@example.com", role: 0 },
  { id: 37, name: "امید", email: "omid@example.com", role: 0 },
  { id: 38, name: "شیرین", email: "shirin@example.com", role: 0 },
  { id: 39, name: "مهران", email: "mehran@example.com", role: 0 },
  { id: 40, name: "نازنین", email: "nazanin2@example.com", role: 0 }
];

const tableHeadersUser = [
    
  "شماره",
  "نام",
  "ایمیل",
  "نقش",
  "ویرایش",
  "بن"
];


const comments = [
  {
    id: 1,
    name: "زهرا کریمی",
    email: "زهرا.کریمی@example.com",
    text: "گینر باعث افزایش وزن خوبی شد بدون چربی زیاد.",
    rating: 4,
    date: "1404/08/06",
  },
  {
    id: 2,
    name: "علی رضایی",
    email: "علی.رضایی@example.com",
    text: "BCAA برای ریکاوری عضلاتم عالی بوده.",
    rating: 4,
    date: "1404/05/11",
  },
  {
    id: 3,
    name: "زهرا کریمی",
    email: "زهرا.کریمی@example.com",
    text: "کراتین مونوهیدرات کیفیت تمرین\u200cهامو بالا برده.",
    rating: 5,
    date: "1403/01/12",
    reply: { name: "مبین محمدی", text: "منم همین تجربه رو داشتم." },
  },
  {
    id: 4,
    name: "سینا احمدی",
    email: "سینا.احمدی@example.com",
    text: "کراتین مونوهیدرات کیفیت تمرین\u200cهامو بالا برده.",
    rating: 3,
    date: "1403/10/04",
    reply: { name: "مبین محمدی", text: "ممنون از نظرت." },
  },
  {
    id: 5,
    name: "زهرا کریمی",
    email: "زهرا.کریمی@example.com",
    text: "از مکمل پروتئین ایزوله خیلی راضی\u200cام.",
    rating: 5,
    date: "1403/06/18",
  },
  {
    id: 6,
    name: "کامبیز مرادی",
    email: "کامبیز.مرادی@example.com",
    text: "کراتین مونوهیدرات کیفیت تمرین\u200cهامو بالا برده.",
    rating: 3,
    date: "1404/12/25",
    reply: { name: "مبین محمدی", text: "موافقم با حرفت." },
  },
  {
    id: 7,
    name: "پارسا تیموری",
    email: "پارسا.تیموری@example.com",
    text: "گینر باعث افزایش وزن خوبی شد بدون چربی زیاد.",
    rating: 3,
    date: "1404/03/27",
  },
  {
    id: 8,
    name: "کامبیز مرادی",
    email: "کامبیز.مرادی@example.com",
    text: "ال-کارنیتین انرژی\u200cم رو بالا برده ولی چربی\u200cسوزیش محسوس نیست.",
    rating: 3,
    date: "1403/05/09",
  },
  {
    id: 9,
    name: "پارسا تیموری",
    email: "پارسا.تیموری@example.com",
    text: "کراتین واقعاً توی افزایش قدرت و حجم عضلانی کمک کرده.",
    rating: 3,
    date: "1403/12/13",
    reply: { name: "مبین محمدی", text: "منم همین تجربه رو داشتم." },
  },
  {
    id: 10,
    name: "علی رضایی",
    email: "علی.رضایی@example.com",
    text: "از مکمل پروتئین ایزوله خیلی راضی\u200cام.",
    rating: 3,
    date: "1404/05/11",
  },
  {
    id: 11,
    name: "الهام حیدری",
    email: "الهام.حیدری@example.com",
    text: "از مکمل پروتئین ایزوله خیلی راضی\u200cام.",
    rating: 4,
    date: "1403/06/21",
    reply: { name: "مبین محمدی", text: "منم همین تجربه رو داشتم." },
  },
  {
    id: 12,
    name: "الهام حیدری",
    email: "الهام.حیدری@example.com",
    text: "BCAA برای ریکاوری عضلاتم عالی بوده.",
    rating: 4,
    date: "1403/05/27",
    reply: { name: "مبین محمدی", text: "ممنون از نظرت." },
  },
  {
    id: 13,
    name: "مهدی محمدی",
    email: "مهدی.محمدی@example.com",
    text: "از مکمل پروتئین ایزوله خیلی راضی\u200cام.",
    rating: 5,
    date: "1403/06/21",
  },
  {
    id: 14,
    name: "ریحانه راد",
    email: "ریحانه.راد@example.com",
    text: "ال-کارنیتین انرژی\u200cم رو بالا برده ولی چربی\u200cسوزیش محسوس نیست.",
    rating: 3,
    date: "1403/03/30",
  },
  {
    id: 15,
    name: "ریحانه راد",
    email: "ریحانه.راد@example.com",
    text: "کراتین واقعاً توی افزایش قدرت و حجم عضلانی کمک کرده.",
    rating: 4,
    date: "1404/05/28",
    reply: { name: "مبین محمدی", text: "موافقم با حرفت." },
  },
  {
    id: 16,
    name: "مهدی محمدی",
    email: "مهدی.محمدی@example.com",
    text: "از مکمل پروتئین ایزوله خیلی راضی\u200cام.",
    rating: 4,
    date: "1404/10/05",
    reply: { name: "مبین محمدی", text: "ممنون از نظرت." },
  },
  {
    id: 17,
    name: "زهرا کریمی",
    email: "زهرا.کریمی@example.com",
    text: "ال-آرژنین به خون\u200cرسانی عضلات کمک کرده.",
    rating: 4,
    date: "1403/01/06",
  },
  {
    id: 18,
    name: "علی رضایی",
    email: "علی.رضایی@example.com",
    text: "کراتین واقعاً توی افزایش قدرت و حجم عضلانی کمک کرده.",
    rating: 3,
    date: "1403/04/22",
  },
  {
    id: 19,
    name: "سینا احمدی",
    email: "سینا.احمدی@example.com",
    text: "ال-آرژنین به خون\u200cرسانی عضلات کمک کرده.",
    rating: 3,
    date: "1403/11/28",
  },
  {
    id: 20,
    name: "الهام حیدری",
    email: "الهام.حیدری@example.com",
    text: "BCAA برای ریکاوری عضلاتم عالی بوده.",
    rating: 5,
    date: "1403/08/29",
    reply: { name: "مبین محمدی", text: "موافقم با حرفت." },
  },
  {
    id: 21,
    name: "نگار سلیمانی",
    email: "نگار.سلیمانی@example.com",
    text: "گینر باعث افزایش وزن خوبی شد بدون چربی زیاد.",
    rating: 3,
    date: "1403/03/20",
    reply: { name: "مبین محمدی", text: "منم همین تجربه رو داشتم." },
  },
  {
    id: 22,
    name: "نوید عباسی",
    email: "نوید.عباسی@example.com",
    text: "ال-کارنیتین انرژی\u200cم رو بالا برده ولی چربی\u200cسوزیش محسوس نیست.",
    rating: 5,
    date: "1403/07/11",
    reply: { name: "مبین محمدی", text: "منم همین تجربه رو داشتم." },
  },
  {
    id: 23,
    name: "مهدی محمدی",
    email: "مهدی.محمدی@example.com",
    text: "از مکمل پروتئین ایزوله خیلی راضی\u200cام.",
    rating: 4,
    date: "1404/07/04",
  },
  {
    id: 24,
    name: "الهام حیدری",
    email: "الهام.حیدری@example.com",
    text: "BCAA برای ریکاوری عضلاتم عالی بوده.",
    rating: 4,
    date: "1403/06/02",
  },
  {
    id: 25,
    name: "زهرا کریمی",
    email: "زهرا.کریمی@example.com",
    text: "ال-کارنیتین انرژی\u200cم رو بالا برده ولی چربی\u200cسوزیش محسوس نیست.",
    rating: 5,
    date: "1404/08/14",
    reply: { name: "مبین محمدی", text: "منم همین تجربه رو داشتم." },
  },
  {
    id: 26,
    name: "پارسا تیموری",
    email: "پارسا.تیموری@example.com",
    text: "کراتین واقعاً توی افزایش قدرت و حجم عضلانی کمک کرده.",
    rating: 4,
    date: "1403/05/13",
  },
  {
    id: 27,
    name: "کامبیز مرادی",
    email: "کامبیز.مرادی@example.com",
    text: "BCAA برای ریکاوری عضلاتم عالی بوده.",
    rating: 5,
    date: "1404/03/04",
  },
  {
    id: 28,
    name: "زهرا کریمی",
    email: "زهرا.کریمی@example.com",
    text: "وی پروتئین طعم خوبی داره و جذبش سریعه.",
    rating: 3,
    date: "1403/05/16",
  },
  {
    id: 29,
    name: "مهدی محمدی",
    email: "مهدی.محمدی@example.com",
    text: "وی پروتئین طعم خوبی داره و جذبش سریعه.",
    rating: 4,
    date: "1404/04/05",
    reply: { name: "مبین محمدی", text: "منم همین تجربه رو داشتم." },
  },
  {
    id: 30,
    name: "علی رضایی",
    email: "علی.رضایی@example.com",
    text: "مولتی\u200cویتامین\u200cها باعث رفع خستگی بعد تمرین شدن.",
    rating: 5,
    date: "1404/11/26",
    reply: { name: "مبین محمدی", text: "منم همین تجربه رو داشتم." },
  },
];


export  {liMenu , dataDashboardMain ,users , comments , tableHeadersUser} 